service: aws-lambda
frameworkVersion: '3'

provider:
  name: aws
  memorySize: 1024
  stage: dev
  timeout: 15
  region: us-east-1
  runtime: nodejs16.x

functions:
  Api:
    handler: handler.Api
    events:
      - http: ANY /{proxy+}
      - http: ANY /

    environment:
      HOST: localhost
      PORT: 3000
      TIMEOUT: 7000
      OWNER: EvanLi
      REPO: Github-Ranking
      REPO_PATH: Data
